// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

//sandbox_manufactura
const SUPABASE_URL = "https://mpwvltwcsqkmlinrlntm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wd3ZsdHdjc3FrbWxpbnJsbnRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4Njk3MDgsImV4cCI6MjA3MjQ0NTcwOH0.fKyFXVEGkhjT0skCVEaHwFQkLNgAeIx9yMbvRf6owVM";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});