// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udfipenqniwaxhdtdxfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkZmlwZW5xbml3YXhoZHRkeGZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NjY1MTcsImV4cCI6MjA3MjQ0MjUxN30.D1dZZTpXAZULniTbFByvXpSIDYfti4_b_3xXSgcZA_A";
// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});