// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxayhrzpyfycmptwulke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14YXlocnpweWZ5Y21wdHd1bGtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDQ2MjUsImV4cCI6MjA2Mzg4MDYyNX0.YtaimKZbbIVIBM-3ke-nrzxGyp7RHZvTvvdzFPdgFoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});